# Generated by Django 4.2.6 on 2023-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oscarbundles", "0002_bundlegroup_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundlegroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
