# Generated by Django 1.11.10 on 2018-03-18 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("oscarbundles", "0006_auto_20180318_1907"),
    ]

    operations = [  # noqa: RUF012
        migrations.DeleteModel("Bundle"),
        migrations.RenameModel("BundleEntry", "Bundle"),
    ]
