services:
  postgres:
    image: postgres:latest@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    command: webpack --watch
    environment:
      NODE_ENV: 'production'
    volumes:
      - ./client/:/oscarbundles/client/
      - ./server/:/oscarbundles/server/

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: python sandbox/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    volumes:
      - ./client/:/oscarbundles/client/
      - ./server/:/oscarbundles/server/
