# Generated by Django 3.2.18 on 2023-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarbundles', '0002_bundlegroup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlegroup',
            name='bundle_type',
            field=models.CharField(choices=[('default', 'Default'), ('upgrade-product', 'Upgrade Products'), ('upgrade-model', 'Upgrade Model'), ('in-configurator-add-on-products', 'In-Configurator Add-On Products'), ('in-configurator-free-gift-products', 'In-Configurator Free Gift Products'), ('post-configurator-add-on-products', 'Post-Configurator Add-On Products'), ('in-basket-add-on-products', 'In-Basket Add-On Products'), ('pdp-buy-together', 'PDP "Buy Together" Section'), ('pillow-qty-upsell', 'Buy a 2nd Pillow for $XX')], default='default', max_length=200, verbose_name='Bundle Type'),
        ),
    ]
