# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20160304_1652'),
        ('oscarbundles', '0002_auto_20160902_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Description of where this bundle type is used.', verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='bundlegroup',
            name='suggested_parents',
            field=models.ManyToManyField(related_name='suggesting_bundle_groups', to='catalogue.Product', verbose_name='Suggested Products'),
        ),
        migrations.AddField(
            model_name='bundlegroup',
            name='triggering_parents',
            field=models.ManyToManyField(related_name='triggering_bundle_groups', to='catalogue.Product', verbose_name='Triggering Products'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oscarbundles.BundleGroup'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bundlegroup',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bundlegroup',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
    ]
