# Generated by Django 3.2.19 on 2023-05-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarbundles', '0003_alter_bundlegroup_bundle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlegroup',
            name='bundle_type',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=200, verbose_name='Bundle Type'),
        ),
    ]
