# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarbundles', '0006_auto_20180318_1907'),
    ]

    operations = [
        migrations.DeleteModel('Bundle'),
        migrations.RenameModel('BundleEntry', 'Bundle'),
    ]
