# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20160304_1652'),
        ('oscarbundles', '0010_auto_20180319_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together=set([('bundle_group', 'triggering_product')]),
        ),
    ]
