# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarbundles', '0011_auto_20180319_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BundleType',
        ),
        migrations.AddField(
            model_name='bundlegroup',
            name='bundle_type',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=200, verbose_name='Bundle Type'),
        ),
    ]
