# Generated by Django 2.1.12 on 2019-09-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarbundles', '0015_auto_20190826_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconfigurablebundle',
            unique_together={('bundle_group', 'triggering_product', 'suggested_range')},
        ),
    ]
